import 'package:flutter/material.dart';

class AppLocalization {
  static final ValueNotifier<bool> languageNotifier = ValueNotifier<bool>(false);

  static bool get isTamil => languageNotifier.value;
  static set isTamil(bool val) {
    languageNotifier.value = val;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome_title': 'Welcome to Your Smart Learning Journey',
      'select_class': 'Select Your Standard',
      'select_medium': 'Select Learning Medium',
      'select_stream': 'Select Academic Stream',
      'english_medium': 'English Medium',
      'tamil_medium': 'Tamil Medium',
      'start_learning': 'Start Learning',
      'ask_ai': 'Ask AI',
      'good_morning': 'Good Morning',
      'ai_learning_assistant': 'AI Learning Assistant',
      'ai_tutor_title': 'Learn Smarter,\nGrow Faster',
      'ai_tutor_subtitle': 'Your personal AI buddy is here to help you learn, solve doubts and achieve your goals!',
      'attendance': 'Attendance',
      'academic_score': 'Academic Score',
      'pending_homework': 'Pending Homework',
      'upcoming_exam': 'Upcoming Exam',
      'learning_streak': 'Learning Streak',
      'reward_coins': 'Reward Coins',
      'subjects': 'Subjects',
      'my_classes': 'My Classes',
      'all_classes': 'All Subjects',
      'my_courses': 'My Courses',
      'my_shelf': 'My Shelf',
      'my_progress': 'My Progress',
      'homework': 'Homework',
      'assignments': 'Assignments',
      'exams': 'Exams',
      'timetable': 'Timetable',
      'results': 'Results',
      'ai_tutor': 'AI Tutor',
      'digital_library': 'Digital Library',
      'mock_tests': 'Mock Tests',
      'career_guidance': 'School Exams',
      'scholarships': 'Scholarships',
      'certificates': 'Certificates',
      'competitions': 'Competitions',
      'announcements': 'Announcements',
      'mathematics': 'Mathematics',
      'science': 'Science',
      'social_science': 'Social Science',
      'physics': 'Physics',
      'chemistry': 'Chemistry',
      'biology': 'Biology',
      'computer_science': 'Computer Science',
      'commerce': 'Commerce',
      'accountancy': 'Accountancy',
      'economics': 'Economics',
      'tamil': 'Tamil',
      'english': 'English',
      'nav_home': 'Home',
      'nav_my_classes': 'My Classes',
      'nav_study': 'Study',
      'nav_homework': 'Homework',
      'nav_achievements': 'Achievements',
      'nav_profile': 'Profile',
      'language_switch': 'தமிழ்',

      // Screen Titles
      'timetable_attendance_title': 'Timetable & Attendance',
      'homework_assignments_title': 'Homework & Assignments',
      'digital_library_title': 'Digital Library',
      'career_guidance_title': 'School Exams & Timetable',
      'scholarships_competitions_title': 'Scholarships & Competitions',
      'announcements_title': 'Announcements',

      // Attendance & Stats
      'overall_attendance': 'Overall Attendance',
      'present': 'Present',
      'absent': 'Absent',
      'leave': 'Leave',

      // Common Subtitles & Banners
      'keep_learning': 'Keep Learning, Keep Growing!',
      'keep_it_up': "Keep it up! Every day counts. You're doing great!",
      'plan_future_title': 'Plan Your Future',
      'plan_future_stream': 'Stream & Career',
      'plan_future_desc': 'Explore top courses, TN college entrance exams, and career roadmaps after 10th and 12th.',
      'school_updates': 'Official School Updates',
      'school_updates_desc': 'Stay updated with exams, events, PTM and official school notices.',
      'discover_plan_achieve': 'Discover. Plan. Achieve.',
      'discover_plan_desc': 'The right guidance today builds a successful tomorrow! 🚀',
      'popular_streams': 'Popular Streams & Career Options',
      'available_scholarships': 'Available Scholarships',
      'state_competitions': 'State Competitions',
      'pending_tasks': 'Pending Tasks',

      // Tabs & Actions
      'filter_all': 'All',
      'filter_exams': 'Exams',
      'filter_circulars': 'Circulars',
      'filter_events': 'Events',
      'filter_holidays': 'Holidays',
      'filter_textbooks': 'Textbooks',
      'filter_notes': 'Notes & PDFs',
      'filter_papers': 'Previous Papers',
      'filter_reference': 'Reference',
      'download_pdf': 'Download PDF',
      'view_details': 'View Details',
      'submit_solution': 'Submit Solution',
      'search_library_hint': 'Search textbooks, notes & model papers...',
      'eligible': 'Eligible',
      'open_for_apply': 'Open for Apply',
      'last_date': 'Last Date',
      'event_date': 'Event Date',
      'prize': 'Prize',
    },
    'ta': {
      'welcome_title': 'உங்கள் அறிவார்ந்த கற்றல் பயணத்திற்கு நல்வரவு',
      'select_class': 'உங்கள் வகுப்பைத் தேர்ந்தெடுக்கவும்',
      'select_medium': 'கற்றல் மொழியைத் தேர்ந்தெடுக்கவும்',
      'select_stream': 'பாடப்பிரிவைத் தேர்ந்தெடுக்கவும்',
      'english_medium': 'ஆங்கில வழி',
      'tamil_medium': 'தமிழ் வழி',
      'start_learning': 'Start Learning',
      'ask_ai': 'AI-யிடம் கேள்',
      'good_morning': 'காலை வணக்கம்',
      'ai_learning_assistant': 'AI Learning Assistant',
      'ai_tutor_title': 'Learn Smarter,\nGrow Faster',
      'ai_tutor_subtitle': 'உங்கள் கற்றல், சந்தேகங்களைத் தீர்ப்பது மற்றும் இலக்குகளை அடைய உங்கள் தனிப்பட்ட AI தோழன் இங்கே உள்ளார்!',
      'attendance': 'வருகைப் பதிவு',
      'academic_score': 'கல்வி மதிப்பெண்',
      'pending_homework': 'நிலுவை வீட்டுப்பாடம்',
      'upcoming_exam': 'அடுத்த தேர்வு',
      'learning_streak': 'தொடர் கற்றல் நாட்கள்',
      'reward_coins': 'பரிசு நாணயங்கள்',
      'subjects': 'பாடங்கள்',
      'my_classes': 'என் வகுப்புகள்',
      'all_classes': 'அனைத்து பாடங்கள்',
      'my_courses': 'என் பாடநெறிகள்',
      'my_shelf': 'என் புத்தக அடுக்கு',
      'my_progress': 'என் முன்னேற்றம்',
      'homework': 'வீட்டுப்பாடம்',
      'assignments': 'ஒப்படைப்புகள்',
      'exams': 'தேர்வுகள்',
      'timetable': 'கால அட்டவணை',
      'results': 'தேர்வு முடிவுகள்',
      'ai_tutor': 'AI ஆசிரியர்',
      'digital_library': 'டிஜிட்டல் நூலகம்',
      'mock_tests': 'மாதிரித் தேர்வுகள்',
      'career_guidance': 'பள்ளித் தேர்வுகள்',
      'scholarships': 'கல்வி உதவித்தொகை',
      'certificates': 'சான்றிதழ்கள்',
      'competitions': 'போட்டிகள்',
      'announcements': 'பள்ளி அறிவிப்புகள்',
      'mathematics': 'கணிதம்',
      'science': 'அறிவியல்',
      'social_science': 'சமூக அறிவியல்',
      'physics': 'இயற்பியல்',
      'chemistry': 'வேதியியல்',
      'biology': 'உயிரியல்',
      'computer_science': 'கணினி அறிவியல்',
      'commerce': 'வணிகவியல்',
      'accountancy': 'கணக்குப்பதிவியல்',
      'economics': 'பொருளியல்',
      'tamil': 'தமிழ்',
      'english': 'ஆங்கிலம்',
      'nav_home': 'முகப்பு',
      'nav_my_classes': 'வகுப்புகள்',
      'nav_study': 'படிப்புகள்',
      'nav_homework': 'வீட்டுப்பாடம்',
      'nav_achievements': 'சாதனைகள்',
      'nav_profile': 'சுயவிவரம்',
      'language_switch': 'English',

      // Screen Titles
      'timetable_attendance_title': 'கால அட்டவணை & வருகை',
      'homework_assignments_title': 'வீட்டுப்பாடம் & பணிகள்',
      'digital_library_title': 'TN டிஜிட்டல் நூலகம்',
      'career_guidance_title': 'பள்ளித் தேர்வுகள் & கால அட்டவணை',
      'scholarships_competitions_title': 'கல்வி உதவித்தொகை & போட்டிகள்',
      'announcements_title': 'பள்ளி அறிவிப்புகள்',

      // Attendance & Stats
      'overall_attendance': 'மொத்த வருகை',
      'present': 'வந்தவர்',
      'absent': 'வராதவர்',
      'leave': 'விடுப்பு',

      // Common Subtitles & Banners
      'keep_learning': 'தொடர்ந்து கற்போம், தொடர்ந்து வளர்வோம்!',
      'keep_it_up': 'தொடர்ந்து சிறப்பாக செய்யுங்கள்! ஒவ்வொரு நாளும் முக்கியம்!',
      'plan_future_title': 'எதிர்காலத்தை திட்டமிடு',
      'plan_future_stream': 'பாடப்பிரிவு & வேலைவாய்ப்பு',
      'plan_future_desc': '10 மற்றும் 12 ஆம் வகுப்பிற்குப் பின் சிறந்த படிப்புகள் மற்றும் நுழைவுத் தேர்வுகளை அறிக.',
      'school_updates': 'அரசு பள்ளி அறிவிப்புகள்',
      'school_updates_desc': 'தேர்வுகள், நிகழ்வுகள், PTM மற்றும் பள்ளி அறிவிப்புகளை உடனுக்குடன் பெறுக.',
      'discover_plan_achieve': 'அறிக. திட்டமிடு. சாதி.',
      'discover_plan_desc': 'இன்றைய சிறந்த வழிகாட்டுதல் நாளைய வெற்றியை உருவாக்கும்! 🚀',
      'popular_streams': 'பிரபலமான பாடப்பிரிவுகள் & வேலைவாய்ப்புகள்',
      'available_scholarships': 'கிடைக்கும் கல்வி உதவித்தொகைகள்',
      'state_competitions': 'மாநில அளவிலான போட்டிகள்',
      'pending_tasks': 'நிலுவையில் உள்ள பணிகள்',

      // Tabs & Actions
      'filter_all': 'அனைத்தும்',
      'filter_exams': 'தேர்வுகள்',
      'filter_circulars': 'சுற்றறிக்கைகள்',
      'filter_events': 'நிகழ்வுகள்',
      'filter_holidays': 'விடுமுறை',
      'filter_textbooks': 'பாடப்புத்தகங்கள்',
      'filter_notes': 'குறிப்புகள் & PDF',
      'filter_papers': 'வினாத்தாள்கள்',
      'filter_reference': 'துணை நூல்கள்',
      'download_pdf': 'PDF பதிவிறக்குக',
      'view_details': 'விவரங்கள்',
      'submit_solution': 'விடை சமர்ப்பிக்க',
      'search_library_hint': 'பாடப்புத்தகங்கள், குறிப்புகளைத் தேடுக...',
      'eligible': 'தகுதியுடையது',
      'open_for_apply': 'விண்ணப்பிக்கலாம்',
      'last_date': 'கடைசி நாள்',
      'event_date': 'நிகழ்வு நாள்',
      'prize': 'பரிசு',
    },
  };

  static String get(String key) {
    String lang = isTamil ? 'ta' : 'en';
    return _localizedValues[lang]?[key] ?? key;
  }
}
